# Generated by Django 5.1.2 on 2025-07-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_s_three_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('retry', 'Retry')], default='uploaded', max_length=20),
        ),
    ]
